services:
  test-db:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_DATABASE: gymbro
      POSTGRESQL_PASSWORD: password123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gymcenters-test"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
